image: collaborating.tuhh.de:5005/cdt5076/gpgpu-sim_distribution/cuda11.8

stages:
  - build
  - test

cache:
  paths:
    - build
    - lib

build:
  stage: build
  script:
    - mkdir -p build
    - cmake -S . -B build
    - make -C build

test:
  stage: test
  script:
    - source new_setup_environment && GPUSIM_CONFIG=test/test.config ./build/test.exe --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: report.xml