image: collaborating.tuhh.de:5005/e-exk5/research/thread-block-cluster/tbc_bench

stages:
  - build
  - test

build:
  tags:
    - cuda
  stage: build
  cache:
    paths:
      - build
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - build/lib/
      - build/bin/
  script:
    - mkdir -p build
    - cmake -G Ninja -S . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - ninja -C build

test:
  tags:
    - cuda
  stage: test
  script:
    - source setup_environment && GPUSIM_CONFIG=test/test.config ./build/bin/test_kernel --gtest_output="xml:report.xml"
  artifacts:
    expire_in: "30 days"
    when: always
    reports:
      junit: report.xml