image: collaborating.tuhh.de:5005/e-exk5/research/thread-block-cluster/tbc_bench

stages:
  - build
  - test

cache:
  paths:
    - build
    - lib

build:
  tags:
    - cuda
  stage: build
  script:
    - mkdir -p build
    - cmake -G Ninja -S . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - ninja -C build

test:
  tags:
    - cuda
  stage: test
  script:
    - source setup_environment && GPUSIM_CONFIG=test/test.config ./build/test.exe --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: report.xml